### ISSUE TITLE
Problem with filter.evt.files.parallel

### ISSUE THREAD

**Issue by fribalet** [uwescience/popcycle#26] opened 2015-01-28 18:20 UTC
# LOAD
library(popcycle)
set.project.location("~/KM_1")
set.cruise.id("KM_1")
set.evt.location("/Volumes/seaflow/KiloMoana_1")

# SELECT AN EVT FILE
evt.list <- get.evt.list() # to get the entire list of evt files
width <- 0.3 # usually between 0.1 and 0.5
notch <- 0.7 # usually between 0.5 and 1

# FILTER
evt.files.without.opp <- filter.evt.files.parallel(evt.list, notch=notch, width=width, cruise=cruise.id, db=db.name, evt.loc=evt.location, cores=4)

**Comment by ctberthiaume** [comment] 2015-02-03 02:21
Fixed in e07f183.  Bug was caused by evt.location not being available to child processes created by Snow.

**Closed by ctberthiaume** 2015-02-03 02:21 UTC
